In [1]:
import torch
import torch.utils.data as Data
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data.dataloader import DataLoader
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

In [2]:
def ReadCSV(csvfile):
    csv = pd.read_csv(csvfile, header=None)
    csv = torch.from_numpy(csv.values)
    return csv

In [3]:
csv_corona = ReadCSV(r"D:\Codes\keyan\peidian\80x3.csv")
label = "corona"
print(csv_corona.shape)

torch.Size([80, 3])


In [4]:
csv_corona = csv_corona.unsqueeze(0).permute(0,2,1)
csv_corona =csv_corona.float()
csv_corona.shape

torch.Size([1, 3, 80])

In [5]:
conv1 = nn.Conv1d(in_channels=3, out_channels=100,kernel_size=10)
LRelu = nn.LeakyReLU()
out1 = conv1(csv_corona)
out1 = LRelu(out1)
out1.shape

torch.Size([1, 100, 71])

In [6]:
conv2 = nn.Conv1d(in_channels=100, out_channels=100, kernel_size=10)
out2 = conv2(out1)
out2 = LRelu(out2)
out2.shape

torch.Size([1, 100, 62])

In [7]:
maxpool1 = nn.MaxPool1d(3)
out3 = maxpool1(out2)
out3.shape

torch.Size([1, 100, 20])

In [8]:
conv3 = nn.Conv1d(in_channels=100, out_channels=160, kernel_size=10)
out4 = conv3(out3)
out4 = LRelu(out4)
out4.shape

torch.Size([1, 160, 11])

In [9]:
conv4 = nn.Conv1d(in_channels=160, out_channels=160, kernel_size=10)
out5 = conv4(out4)
out5 = LRelu(out5)
out5.shape

torch.Size([1, 160, 2])

In [10]:
avgpool = nn.AvgPool1d(2)
out6 = avgpool(out5)

torch.Size([1, 160, 2])

In [13]:
dout = nn.Dropout(p=0.5)
out7 = dout(out6)
out7.shape

torch.Size([1, 160, 1])

In [32]:
fc = nn.Linear(160, 5)
out8 = fc(out7.permute(0,2,1))
print(out8)

tensor([[[-3.7281e-01,  1.3647e+00, -2.6163e-03,  1.7717e+00, -2.9950e+00]]],
       grad_fn=<AddBackward0>)


In [35]:
smax = nn.Softmax()
out9 = smax(out8)
print(out9)

tensor([[[1., 1., 1., 1., 1.]]], grad_fn=<SoftmaxBackward>)


In [21]:
m = nn.Softmax()
input = torch.randn(2,3)
print(input)
output = m(input)
print(output)

tensor([[ 0.3300,  0.6291, -0.1977],
        [ 1.8818, -0.0753,  1.1090]])
tensor([[0.3403, 0.4589, 0.2008],
        [0.6238, 0.0881, 0.2880]])


In [25]:
e = torch.exp(input)
es = e.sum()

In [26]:
e

tensor([[1.3910, 1.8759, 0.8207],
        [6.5655, 0.9275, 3.0315]])

In [28]:
es

tensor(14.6120)

In [36]:
x = [-3.7281e-01,  1.3647e+00, -2.6163e-03,  1.7717e+00, -2.9950e+00]

[-0.37281, 1.3647, -0.0026163, 1.7717, -2.995]

In [46]:
labels = ('internal_discharge', 'corona_discharge', 'corona_discharge', 'internal_discharge')

In [47]:
labels = list(labels)
print(labels)
print(type(labels[0][1]))

['internal_discharge', 'corona_discharge', 'corona_discharge', 'internal_discharge']
<class 'str'>


In [53]:
x = torch.tensor(labels[0])

TypeError: new(): invalid data type 'str'

In [54]:
x = ('2', '2', '2', '2')

In [61]:
y = list(map(int, x))

In [63]:
z = torch.tensor(y)
print(z)

tensor([2, 2, 2, 2])


In [65]:
def tuple2tensor_char(x):
    return torch.tensor(list(map(int, x)))

ValueError: invalid literal for int() with base 10: 'internal_discharge'